<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-M01B47M" name="basictesting.Actitime_TimeOut" tests="1" failures="0" timestamp="03 Jan 2023 15:46:02 GMT" time="0.222" errors="1">
  <testcase name="OpenBrowserAndAppUrl" time="0.222" classname="basictesting.Actitime_TimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method basictesting.Actitime_TimeOut.OpenBrowserAndAppUrl() didn&#039;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method basictesting.Actitime_TimeOut.OpenBrowserAndAppUrl() didn't finish within the time-out 200
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- OpenBrowserAndAppUrl -->
</testsuite> <!-- basictesting.Actitime_TimeOut -->
