<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-M01B47M" name="basictesting.Actitime_ExceptionAndTimeOut" tests="2" failures="0" timestamp="03 Jan 2023 15:23:23 GMT" time="1.029" errors="1">
  <testcase name="divideByZeroExample" time="0.014" classname="basictesting.Actitime_ExceptionAndTimeOut"/>
  <testcase name="executeTimeout" time="1.015" classname="basictesting.Actitime_ExceptionAndTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method basictesting.Actitime_ExceptionAndTimeOut.executeTimeout() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method basictesting.Actitime_ExceptionAndTimeOut.executeTimeout() didn't finish within the time-out 1000
at sun.misc.Unsafe.compareAndSwapInt(Native Method)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.compareAndSetState(Unknown Source)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(Unknown Source)
at java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- executeTimeout -->
</testsuite> <!-- basictesting.Actitime_ExceptionAndTimeOut -->
