<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-M01B47M" name="basictestng.Actitime_ExceptionAndTimeOut" tests="1" failures="0" timestamp="12 Jan 2023 15:32:22 GMT" time="1.079" errors="1">
  <testcase name="executeTimeout" time="1.079" classname="basictestng.Actitime_ExceptionAndTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method basictestng.Actitime_ExceptionAndTimeOut.executeTimeout() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method basictestng.Actitime_ExceptionAndTimeOut.executeTimeout() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- executeTimeout -->
</testsuite> <!-- basictestng.Actitime_ExceptionAndTimeOut -->
